<?php

namespace AppBundle\Repository;

/**
 * ModuleDWRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleDwRepository extends \Doctrine\ORM\EntityRepository
{
}
