<?php

namespace AppBundle\Repository;

/**
 * ModuleGERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleGeRepository extends \Doctrine\ORM\EntityRepository
{
}
