<?php

namespace AppBundle\Repository;

/**
 * ModuleLTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleLtRepository extends \Doctrine\ORM\EntityRepository
{
}
