<?php

namespace AppBundle\Repository;

/**
 * ModuleQuestionHeadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleQuestionHeadingRepository extends \Doctrine\ORM\EntityRepository
{
}
