<?php

namespace AppBundle\Repository;

/**
 * ModuleQuestionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleQuestionItemRepository extends \Doctrine\ORM\EntityRepository
{
}
