<?php

namespace AppBundle\Repository;

/**
 * ModuleCnKeywordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleCnKeywordRepository extends \Doctrine\ORM\EntityRepository
{
}
