<?php

namespace AppBundle\Repository;

/**
 * ModuleCNRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleCnRepository extends \Doctrine\ORM\EntityRepository
{
}
