<?php

namespace AppBundle\Repository;

/**
 * ModuleQURepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleQuRepository extends \Doctrine\ORM\EntityRepository
{
}
