<?php

namespace AppBundle\Repository;

/**
 * ModuleLSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleLsRepository extends \Doctrine\ORM\EntityRepository
{
}
