<?php

namespace AppBundle\Repository;

/**
 * PasswordResetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordResetRepository extends \Doctrine\ORM\EntityRepository
{
}
