# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        clspdb_provider:
            entity:
                class: AppBundle:User
                property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            provider: clspdb_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        # require ROLE_STUDENT for /student*
        - { path: ^/student, roles: ROLE_STUDENT }

        # require ROLE_PROFESSOR for /professor*
        - { path: ^/professor, roles: ROLE_PROFESSOR}

        # require ROLE_DESIGNER for /designer*
        - { path: ^/designer, roles: ROLE_DESIGNER }

        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
