# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.valid_signup_code_validator:
            class: AppBundle\Validator\Constraints\ValidSignupCodeValidator
            tags:
                - { name: validator.constraint_validator }
    cors_listener:
        class: AppBundle\Listener\CORSListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    json_listener:
            class: AppBundle\Listener\JsonRequestTransformerListener
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
