<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Media
 *
 * @ORM\Table(name="media")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\MediaRepository")
 */
class Media
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $name Name for file (autofilled from original filename or custom)
     *
     * @ORM\Column(type = "string", length = 255)
     */
    private $name;

    /**
     * @var string $filename randomly generated unique name for file
     *
     * @ORM\Column(type = "string", length = 64)
     */
    private $filename;

    /**
     * @var string $fileType
     *
     * @ORM\Column(type = "string", length = 64)
     */
    private $fileType;

    /**
     * Many Media have One Song.
     * @ORM\ManyToOne(targetEntity="Song", inversedBy="media")
     * @ORM\JoinColumn(name="song_id", referencedColumnName="id")
     */
    private $song;

    /**
     * Many Media have One ModuleCnKeyword.
     * @ORM\ManyToOne(targetEntity="ModuleCnKeyword", inversedBy="media")
     * @ORM\JoinColumn(name="keyword_id", referencedColumnName="id")
     */
    private $moduleCnKeyword;


    /*********************************
     * Autogenerated getters/setters *
     *********************************
     */

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Media
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set filename
     *
     * @param string $filename
     *
     * @return Media
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * Get filename
     *
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set fileType
     *
     * @param string $fileType
     *
     * @return Media
     */
    public function setFileType($fileType)
    {
        $this->fileType = $fileType;

        return $this;
    }

    /**
     * Get fileType
     *
     * @return string
     */
    public function getFileType()
    {
        return $this->fileType;
    }

    /**
     * Set moduleCnKeyword
     *
     * @param \AppBundle\Entity\Song $moduleCnKeyword
     *
     * @return Media
     */
    public function setModuleCnKeyword(\AppBundle\Entity\Song $moduleCnKeyword = null)
    {
        $this->moduleCnKeyword = $moduleCnKeyword;

        return $this;
    }

    /**
     * Get moduleCnKeyword
     *
     * @return \AppBundle\Entity\Song
     */
    public function getModuleCnKeyword()
    {
        return $this->moduleCnKeyword;
    }

    /**
     * Set product
     *
     * @param \AppBundle\Entity\ModuleCnKeyword $product
     *
     * @return Media
     */
    public function setProduct(\AppBundle\Entity\ModuleCnKeyword $product = null)
    {
        $this->product = $product;

        return $this;
    }

    /**
     * Get product
     *
     * @return \AppBundle\Entity\ModuleCnKeyword
     */
    public function getProduct()
    {
        return $this->product;
    }
}
