<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * ModuleCnKeyword
 *
 * @ORM\Table(name="module_cn_keyword")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ModuleCnKeywordRepository")
 */
class ModuleCnKeyword
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length = 1000)
     */
    private $phrase;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length = 1000, nullable=true)
     */
    private $link;

    /**
     * Many ModuleCnKeywords have One ModuleCn.
     * @ORM\ManyToOne(targetEntity="ModuleCn", inversedBy="keywords")
     * @ORM\JoinColumn(name="cn_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $moduleCn;

    /**
     * Many ModuleCnKeyword has Many Media
     * @ORM\ManyToMany(targetEntity="Media", inversedBy="keywords")
     * @ORM\JoinTable(name="module_cn_keywords_media")
     */
    private $media;

    public function __construct() {
        $this->media = new ArrayCollection();
    }

    /*********************************
     * Autogenerated getters/setters *
     *********************************
     */











    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set phrase
     *
     * @param string $phrase
     *
     * @return ModuleCnKeyword
     */
    public function setPhrase($phrase)
    {
        $this->phrase = $phrase;

        return $this;
    }

    /**
     * Get phrase
     *
     * @return string
     */
    public function getPhrase()
    {
        return $this->phrase;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return ModuleCnKeyword
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set link
     *
     * @param string $link
     *
     * @return ModuleCnKeyword
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Get link
     *
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Set moduleCn
     *
     * @param \AppBundle\Entity\ModuleCn $moduleCn
     *
     * @return ModuleCnKeyword
     */
    public function setModuleCn(\AppBundle\Entity\ModuleCn $moduleCn = null)
    {
        $this->moduleCn = $moduleCn;

        return $this;
    }

    /**
     * Get moduleCn
     *
     * @return \AppBundle\Entity\ModuleCn
     */
    public function getModuleCn()
    {
        return $this->moduleCn;
    }

    /**
     * Add medium
     *
     * @param \AppBundle\Entity\Media $medium
     *
     * @return ModuleCnKeyword
     */
    public function addMedia(\AppBundle\Entity\Media $medium)
    {
        $this->media[] = $medium;

        return $this;
    }

    /**
     * Remove medium
     *
     * @param \AppBundle\Entity\Media $medium
     */
    public function removeMedia(\AppBundle\Entity\Media $medium)
    {
        $this->media->removeElement($medium);
    }

    /**
     * Get media
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMedia()
    {
        return $this->media;
    }
}
