<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * ModuleQuestionHeading
 *
 * @ORM\Table(name="module_question_heading")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ModuleQuestionHeadingRepository")
 */
class ModuleQuestionHeading
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length = 255)
     */
    private $name;

    /**
     * One Question Heading has Many Questions.
     * @ORM\OneToMany(targetEntity="ModuleQuestionItem", mappedBy="heading")
     */
    private $questions;

    /**
     * Many Question Headings have One ModuleQu.
     * @ORM\ManyToOne(targetEntity="ModuleQu", inversedBy="headings")
     * @ORM\JoinColumn(name="qu_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $moduleQu;

    /**
     * Many Question Headings have One ModuleLt.
     * @ORM\ManyToOne(targetEntity="ModuleLt", inversedBy="headings")
     * @ORM\JoinColumn(name="lt_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $moduleLt;

    /**
     * Many Question Headings have One ModuleGe.
     * @ORM\ManyToOne(targetEntity="ModuleGe", inversedBy="headings")
     * @ORM\JoinColumn(name="ge_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $moduleGe;

    /**
     * Many Question Headings have One ModuleDw.
     * @ORM\ManyToOne(targetEntity="ModuleDw", inversedBy="headings")
     * @ORM\JoinColumn(name="dw_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $moduleDw;

    /**
     * Many Question Headings have One ModuleLs.
     * @ORM\ManyToOne(targetEntity="ModuleLs", inversedBy="headings")
     * @ORM\JoinColumn(name="ls_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $moduleLs;

    /**
     * @var integer $weight Heading Weight (affects how the headers will be ordered)
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $weight;

    public function __construct() {
        $this->questions = new ArrayCollection();
    }


    /*********************************
     * Autogenerated getters/setters *
     *********************************
     */

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return ModuleQuestionHeading
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Add question
     *
     * @param \AppBundle\Entity\ModuleQuestionItem $question
     *
     * @return ModuleQuestionHeading
     */
    public function addQuestion(\AppBundle\Entity\ModuleQuestionItem $question)
    {
        $this->questions[] = $question;

        return $this;
    }

    /**
     * Remove question
     *
     * @param \AppBundle\Entity\ModuleQuestionItem $question
     */
    public function removeQuestion(\AppBundle\Entity\ModuleQuestionItem $question)
    {
        $this->questions->removeElement($question);
    }

    /**
     * Get questions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getQuestions()
    {
        return $this->questions;
    }

    /**
     * Set moduleQu
     *
     * @param \AppBundle\Entity\ModuleQu $moduleQu
     *
     * @return ModuleQuestionHeading
     */
    public function setModuleQu(\AppBundle\Entity\ModuleQu $moduleQu = null)
    {
        $this->moduleQu = $moduleQu;

        return $this;
    }

    /**
     * Get moduleQu
     *
     * @return \AppBundle\Entity\ModuleQu
     */
    public function getModuleQu()
    {
        return $this->moduleQu;
    }

    /**
     * Set moduleLt
     *
     * @param \AppBundle\Entity\ModuleLt $moduleLt
     *
     * @return ModuleQuestionHeading
     */
    public function setModuleLt(\AppBundle\Entity\ModuleLt $moduleLt = null)
    {
        $this->moduleLt = $moduleLt;

        return $this;
    }

    /**
     * Get moduleLt
     *
     * @return \AppBundle\Entity\ModuleLt
     */
    public function getModuleLt()
    {
        return $this->moduleLt;
    }

    /**
     * Set moduleGe
     *
     * @param \AppBundle\Entity\ModuleGe $moduleGe
     *
     * @return ModuleQuestionHeading
     */
    public function setModuleGe(\AppBundle\Entity\ModuleGe $moduleGe = null)
    {
        $this->moduleGe = $moduleGe;

        return $this;
    }

    /**
     * Get moduleGe
     *
     * @return \AppBundle\Entity\ModuleGe
     */
    public function getModuleGe()
    {
        return $this->moduleGe;
    }

    /**
     * Set moduleDw
     *
     * @param \AppBundle\Entity\ModuleDw $moduleDw
     *
     * @return ModuleQuestionHeading
     */
    public function setModuleDw(\AppBundle\Entity\ModuleDw $moduleDw = null)
    {
        $this->moduleDw = $moduleDw;

        return $this;
    }

    /**
     * Get moduleDw
     *
     * @return \AppBundle\Entity\ModuleDw
     */
    public function getModuleDw()
    {
        return $this->moduleDw;
    }

    /**
     * Set moduleLs
     *
     * @param \AppBundle\Entity\ModuleLs $moduleLs
     *
     * @return ModuleQuestionHeading
     */
    public function setModuleLs(\AppBundle\Entity\ModuleLs $moduleLs = null)
    {
        $this->moduleLs = $moduleLs;

        return $this;
    }

    /**
     * Get moduleLs
     *
     * @return \AppBundle\Entity\ModuleLs
     */
    public function getModuleLs()
    {
        return $this->moduleLs;
    }

    /**
     * Set weight
     *
     * @param integer $weight
     *
     * @return ModuleQuestionHeading
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;

        return $this;
    }

    /**
     * Get weight
     *
     * @return integer
     */
    public function getWeight()
    {
        return $this->weight;
    }
}
